project:
  type: website
  output-dir: docs
  

website:
  title: "Jordan Sibley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    page-layout: full

editor: visual

