project:
  type: website
  output-dir: docs
  

website:
  title: "Jordan Sibley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
  page-footer:
    background: light
    left: Copyright 2024, Jordan Sibley
    right: This website is built with {{< fa brands github title="the octocat github icon">}}, {{< fa brands r-project title="the R icon">}}, and Quarto

format:
  html:
    theme: styles.scss
    mainfont: Ubuntu
    toc: false
    page-layout: full


